### ISSUE TITLE
package can't build

### ISSUE THREAD

**Issue by ghost** [elastic/logstash-forwarder#177]
I try execute go build on debian wheezy with golang 1.0.2-1.1

root@server:/home/user/logstash-forwarder# go build
# _/home/user/logstash-forwarder
./syslog.go:11: undefined: syslog.LOG_DAEMON
